[package]
name = "find-and-replace"
version = "1.0.0"
authors = ["Cecile Tonglet <cecile.tonglet@collibra.com>"]
description = "Tool to find and replace, recursively in a directory using globs, file content using a regular expression"

[dependencies]
glob = "0.2"
regex = "1"
clap = "2.32"
